import { createContext, useContext } from "react";
import type { LocationAggregate } from "../shared/case-aggregate";
import type { NewsArticle } from "../shared/news";

// SSR data plumbing.
// The server renders the initial HTML with location + news data already populated,
// embeds the same payload into the document via a `window.__HANTA_SSR__` global,
// and the client reads it on boot to hydrate identically without an extra fetch.

// Meta block describing the freshness/shape of the rendered dataset.
// Surfaced in the UI header so users know when the data was generated.
export interface SSRMeta {
  totalCases: number;
  countries: number;
  locations: number;
  // ISO timestamp the underlying data file was generated by the scraper.
  generatedAt: string | null;
  // ISO timestamp this HTML was rendered on the server.
  loadedAt: string;
}

// Full SSR payload — everything the page needs to render its first paint.
export interface SSRData {
  locations: LocationAggregate[];
  meta: SSRMeta | null;
  news: NewsArticle[];
}

// Global key under which the server stores the JSON payload on `window`.
// Kept in one place so server and client stay in sync.
export const SSR_DATA_GLOBAL = "__HANTA_SSR__";

// React context carrying the SSR payload through the tree.
const SSRContext = createContext<SSRData | null>(null);

// Re-export the provider so callers don't import the context directly.
export const SSRDataProvider = SSRContext.Provider;

// Hook used by components to access the SSR payload during render.
// Returns null when called outside the provider (defensive — should not happen in production).
export function useSSRData(): SSRData | null {
  return useContext(SSRContext);
}

// Read the SSR payload off `window` during client hydration.
// Casts through `unknown` because we don't want to widen the global Window type
// just for this single read — the runtime check below guards the shape.
export function readSSRDataFromWindow(): SSRData | null {
  const g = globalThis as unknown as Record<string, unknown>;
  const raw = g[SSR_DATA_GLOBAL];
  if (!raw || typeof raw !== "object") return null;
  return raw as SSRData;
}
