// Shared case-level types used by both the scraper (producer) and the API/UI (consumers).
// These are the canonical per-case shapes — keep client and server in sync via this file.

// Status labels accepted by the pipeline.
// The list is a const tuple so we can derive `CaseStatus` from it and validate at runtime
// without duplicating the literal set in two places.
export const VALID_STATUSES = [
  "Confirmed",
  "Probable",
  "Suspected",
  "Deceased",
  "Monitoring",
] as const;

// Union of the literal strings above; used wherever a typed status is required.
export type CaseStatus = (typeof VALID_STATUSES)[number];

// A single normalized case as it lives in storage and on the public API.
// Field naming is camelCase to match JSON output of the API.
export interface Case {
  // Stable internal identifier (deduplication key); generated by the scraper.
  caseId: string;
  // Source-provided id when available, retained for cross-referencing the original record.
  nativeId?: string;
  // Normalized status; see VALID_STATUSES.
  status: CaseStatus;
  // ISO-8601 timestamp the source reported the case (not when we ingested it).
  dateReported: string;
  // Source identifier (e.g. "who", "cdc"); see scraper/sources for the registry.
  source: string;
  // Geographic coordinates resolved by the reverse geocoder when possible.
  latitude: number;
  longitude: number;
  // Human-readable location string as resolved/aggregated.
  locationName: string;
  // Hantavirus strain or variant when known (free-text upstream).
  virusStrain: string;
  // ISO-8601 timestamp recording when the source was last verified during this run.
  sourceVerifiedAt: string;
  // Free-form notes carried through from upstream extraction.
  notes: string;
}

// Per-source telemetry emitted by each scraper source after its run.
// Surfaced through /api/v1/sources so the UI can show health and last-run stats.
export interface SourceRunStats {
  status: "ok" | "error";
  casesCollected?: number;
  verifiedAt?: string;
  error?: string;
}
